modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/gravestone/issues"
[[mods]]
modId = "gravestone"
version = "${mod_version}"
displayName = "Gravestone Mod"
updateJSONURL = "https://update.maxhenkel.de/neoforge/gravestone"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/gravestone-mod"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Places a gravestone with your inventory items inside when you die'''
[[dependencies.gravestone]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.gravestone]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.gravestone]]
modId = "jade"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"